<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $categories = [
            [
                'name_ar' => 'اقمشة',
                'name_en' => 'Fabrics',
                'description_ar' => 'تصنيف الاقمشة',
                'description_en' => 'Fabrics category',
                'slug_en' => 'fabrics',
                'slug_ar' => 'اقمشة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيام',
                'name_en' => 'Tents',
                'description_ar' => 'تصنيف الخيام',
                'description_en' => 'Tents category',
                'slug_en' => 'tents',
                'slug_ar' => 'خيام',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسات بر',
                'name_en' => 'Outdoor Seating',
                'description_ar' => 'تصنيف جلسات البر',
                'description_en' => 'Outdoor seating category',
                'slug_en' => 'outdoor-seating',
                'slug_ar' => 'جلسات-بر',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'أغطية وملحقات',
                'name_en' => 'Covers and Accessories',
                'description_ar' => 'تصنيف الأغطية والملحقات',
                'description_en' => 'Covers and accessories category',
                'slug_en' => 'covers-accessories',
                'slug_ar' => 'اغطية-ملحقات',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'إضاءة خارجية',
                'name_en' => 'Outdoor Lighting',
                'description_ar' => 'تصنيف الإضاءة الخارجية',
                'description_en' => 'Outdoor lighting category',
                'slug_en' => 'outdoor-lighting',
                'slug_ar' => 'اضاءة-خارجية',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'أدوات التخييم',
                'name_en' => 'Camping Tools',
                'description_ar' => 'تصنيف أدوات التخييم',
                'description_en' => 'Camping tools category',
                'slug_en' => 'camping-tools',
                'slug_ar' => 'ادوات-التخييم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('categories')->upsert($categories, ['slug_ar'], ['name_ar', 'name_en', 'description_ar', 'description_en', 'created_at', 'updated_at']);

        $sub_categories = [
            [
                'name_ar' => 'اقمشة داخلية',
                'name_en' => 'Indoor Fabrics',
                'description_ar' => 'تصنيف الاقمشة الداخلية',
                'description_en' => 'Indoor fabrics category',
                'slug_en' => 'indoor-fabrics',
                'slug_ar' => 'اقمشة-داخلية',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'اقمشة خارجية',
                'name_en' => 'Outdoor Fabrics',
                'description_ar' => 'تصنيف الاقمشة الخارجية',
                'description_en' => 'Outdoor fabrics category',
                'slug_en' => 'outdoor-fabrics',
                'slug_ar' => 'اقمشة-خارجية',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'اقمشة قطنية',
                'name_en' => 'Cotton Fabrics',
                'description_ar' => 'تصنيف الاقمشة القطنية',
                'description_en' => 'Cotton fabrics category',
                'slug_en' => 'cotton-fabrics',
                'slug_ar' => 'اقمشة-قطنية',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيام بر',
                'name_en' => 'Camping Tents',
                'description_ar' => 'تصنيف خيام البر',
                'description_en' => 'Camping tents category',
                'slug_en' => 'camping-tents',
                'slug_ar' => 'خيام-بر',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيام عائلية',
                'name_en' => 'Family Tents',
                'description_ar' => 'تصنيف الخيام العائلية',
                'description_en' => 'Family tents category',
                'slug_en' => 'family-tents',
                'slug_ar' => 'خيام-عائلية',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيام للأطفال',
                'name_en' => 'Kids Tents',
                'description_ar' => 'تصنيف خيام الأطفال',
                'description_en' => 'Kids tents category',
                'slug_en' => 'kids-tents',
                'slug_ar' => 'خيام-للأطفال',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسات بر فاخرة',
                'name_en' => 'Luxury Outdoor Seating',
                'description_ar' => 'تصنيف جلسات البر الفاخرة',
                'description_en' => 'Luxury outdoor seating category',
                'slug_en' => 'luxury-outdoor-seating',
                'slug_ar' => 'جلسات-بر-فاخرة',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسات بر اقتصادية',
                'name_en' => 'Budget Outdoor Seating',
                'description_ar' => 'تصنيف جلسات البر الاقتصادية',
                'description_en' => 'Budget outdoor seating category',
                'slug_en' => 'budget-outdoor-seating',
                'slug_ar' => 'جلسات-بر-اقتصادية',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'أغطية الخيام',
                'name_en' => 'Tent Covers',
                'description_ar' => 'تصنيف أغطية الخيام',
                'description_en' => 'Tent covers category',
                'slug_en' => 'tent-covers',
                'slug_ar' => 'اغطية-خيام',
                'parent_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'ملحقات الخيام',
                'name_en' => 'Tent Accessories',
                'description_ar' => 'تصنيف ملحقات الخيام',
                'description_en' => 'Tent accessories category',
                'slug_en' => 'tent-accessories',
                'slug_ar' => 'ملحقات-خيام',
                'parent_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'مصابيح LED',
                'name_en' => 'LED Lights',
                'description_ar' => 'تصنيف مصابيح LED الخارجية',
                'description_en' => 'Outdoor LED lights category',
                'slug_en' => 'led-lights',
                'slug_ar' => 'مصابيح-led',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'فوانيس وشموع',
                'name_en' => 'Lanterns and Candles',
                'description_ar' => 'تصنيف الفوانيس والشموع',
                'description_en' => 'Lanterns and candles category',
                'slug_en' => 'lanterns-candles',
                'slug_ar' => 'فوانيس-شموع',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'أدوات الطهي',
                'name_en' => 'Cooking Tools',
                'description_ar' => 'تصنيف أدوات الطهي الخارجية',
                'description_en' => 'Outdoor cooking tools category',
                'slug_en' => 'cooking-tools',
                'slug_ar' => 'ادوات-الطهي',
                'parent_id' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'أكياس النوم',
                'name_en' => 'Sleeping Bags',
                'description_ar' => 'تصنيف أكياس النوم',
                'description_en' => 'Sleeping bags category',
                'slug_en' => 'sleeping-bags',
                'slug_ar' => 'اكياس-النوم',
                'parent_id' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        DB::table('categories')->upsert($sub_categories, ['slug_ar'], ['name_ar', 'name_en', 'description_ar', 'description_en', 'parent_id', 'created_at', 'updated_at']);
    }
}
