<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();


        $fabrics = Category::where('slug_en', 'indoor-fabrics')->first();
        $tents = Category::where('slug_en', 'camping-tents')->first();
        $seating = Category::where('slug_en', 'luxury-outdoor-seating')->first();
        $khayma_Brand = Brand::where('slug_en', 'khayma')->first();

        $products = [
            [
                'name_ar' => 'قماش مقاوم للماء',
                'name_en' => 'Waterproof Fabric',
                'description_ar' => 'قماش عالي الجودة مقاوم للماء والعوامل الجوية',
                'description_en' => 'High quality fabric resistant to water and weather',
                'slug_ar' => 'قماش-مقاوم-للماء',
                'slug_en' => 'waterproof-fabric',
                'category_id' => $fabrics->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'قماش مقاوم للماء للبيع',
                'meta_title_en' => 'Waterproof Fabric for Sale',
                'meta_description_ar' => 'أفضل قماش مقاوم للماء مناسب للاستخدام الخارجي',
                'meta_description_en' => 'Best waterproof fabric suitable for outdoor use',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيمة بر عائلية',
                'name_en' => 'Family Tent',
                'description_ar' => 'خيمة بر واسعة مناسبة للعائلات والرحلات',
                'description_en' => 'Spacious family tent for camping and trips',
                'slug_ar' => 'خيمة-بر-عائلية',
                'slug_en' => 'family-tent',
                'category_id' => $tents->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'خيمة بر عائلية فاخرة',
                'meta_title_en' => 'Luxury Family Tent',
                'meta_description_ar' => 'خيمة قوية تتحمل الظروف الصحراوية',
                'meta_description_en' => 'Durable tent that withstands desert conditions',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسة بر فاخرة',
                'name_en' => 'Luxury Outdoor Seating',
                'description_ar' => 'جلسة بر مريحة بتصميم عصري',
                'description_en' => 'Comfortable outdoor seating with modern design',
                'slug_ar' => 'جلسة-بر-فاخرة',
                'slug_en' => 'luxury-outdoor-seating',
                'category_id' => $seating->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'جلسات بر فاخرة',
                'meta_title_en' => 'Luxury Outdoor Seating',
                'meta_description_ar' => 'أفضل جلسات بر للرحلات والاستجمام',
                'meta_description_en' => 'Best outdoor seating for camping and relaxation',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'قماش قطني طبيعي',
                'name_en' => 'Natural Cotton Fabric',
                'description_ar' => 'قماش قطني عضوي مناسب للاستخدام الداخلي والخارجي',
                'description_en' => 'Organic cotton fabric suitable for indoor and outdoor use',
                'slug_ar' => 'قماش-قطني-طبيعي',
                'slug_en' => 'natural-cotton-fabric',
                'category_id' => $fabrics->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'قماش قطني طبيعي',
                'meta_title_en' => 'Natural Cotton Fabric',
                'meta_description_ar' => 'قماش قطني عالي الجودة للديكور والملابس',
                'meta_description_en' => 'High quality cotton fabric for decor and clothing',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيمة بر فردية',
                'name_en' => 'Single Person Tent',
                'description_ar' => 'خيمة بر خفيفة الوزن للشخص الواحد',
                'description_en' => 'Lightweight tent for one person',
                'slug_ar' => 'خيمة-بر-فردية',
                'slug_en' => 'single-person-tent',
                'category_id' => $tents->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'خيمة بر فردية',
                'meta_title_en' => 'Single Person Tent',
                'meta_description_ar' => 'خيمة مثالية للمغامرات الفردية',
                'meta_description_en' => 'Perfect tent for solo adventures',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسة بر قابلة للطي',
                'name_en' => 'Foldable Outdoor Chair',
                'description_ar' => 'كرسي بر قابل للطي سهل الحمل',
                'description_en' => 'Foldable outdoor chair easy to carry',
                'slug_ar' => 'جلسة-بر-قابلة-للطي',
                'slug_en' => 'foldable-outdoor-chair',
                'category_id' => $seating->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'كرسي بر قابل للطي',
                'meta_title_en' => 'Foldable Outdoor Chair',
                'meta_description_ar' => 'كرسي مريح للرحلات والتخييم',
                'meta_description_en' => 'Comfortable chair for trips and camping',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'قماش مقاوم للشمس',
                'name_en' => 'Sun Resistant Fabric',
                'description_ar' => 'قماش يحمي من أشعة الشمس الضارة',
                'description_en' => 'Fabric that protects from harmful sun rays',
                'slug_ar' => 'قماش-مقاوم-للشمس',
                'slug_en' => 'sun-resistant-fabric',
                'category_id' => $fabrics->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'قماش مقاوم للشمس',
                'meta_title_en' => 'Sun Resistant Fabric',
                'meta_description_ar' => 'قماش مثالي للستائر والمظلات',
                'meta_description_en' => 'Ideal fabric for curtains and awnings',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيمة بر للأطفال',
                'name_en' => 'Kids Camping Tent',
                'description_ar' => 'خيمة بر ممتعة للأطفال',
                'description_en' => 'Fun camping tent for kids',
                'slug_ar' => 'خيمة-بر-للأطفال',
                'slug_en' => 'kids-camping-tent',
                'category_id' => $tents->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'خيمة بر للأطفال',
                'meta_title_en' => 'Kids Camping Tent',
                'meta_description_ar' => 'خيمة آمنة وممتعة للأطفال',
                'meta_description_en' => 'Safe and fun tent for children',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسة بر مع مظلة',
                'name_en' => 'Outdoor Chair with Umbrella',
                'description_ar' => 'جلسة بر مع مظلة شمسية',
                'description_en' => 'Outdoor chair with sun umbrella',
                'slug_ar' => 'جلسة-بر-مع-مظلة',
                'slug_en' => 'outdoor-chair-with-umbrella',
                'category_id' => $seating->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'جلسة بر مع مظلة',
                'meta_title_en' => 'Outdoor Chair with Umbrella',
                'meta_description_ar' => 'جلسة مريحة مع حماية من الشمس',
                'meta_description_en' => 'Comfortable seating with sun protection',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'قماش مقاوم للحريق',
                'name_en' => 'Fire Resistant Fabric',
                'description_ar' => 'قماش آمن مقاوم للحريق',
                'description_en' => 'Safe fabric resistant to fire',
                'slug_ar' => 'قماش-مقاوم-للحريق',
                'slug_en' => 'fire-resistant-fabric',
                'category_id' => $fabrics->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'قماش مقاوم للحريق',
                'meta_title_en' => 'Fire Resistant Fabric',
                'meta_description_ar' => 'قماش آمن للاستخدام في الأماكن العامة',
                'meta_description_en' => 'Safe fabric for public spaces',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيمة بر كبيرة',
                'name_en' => 'Large Camping Tent',
                'description_ar' => 'خيمة بر كبيرة للمجموعات',
                'description_en' => 'Large tent for groups',
                'slug_ar' => 'خيمة-بر-كبيرة',
                'slug_en' => 'large-camping-tent',
                'category_id' => $tents->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'خيمة بر كبيرة',
                'meta_title_en' => 'Large Camping Tent',
                'meta_description_ar' => 'خيمة واسعة للرحلات الجماعية',
                'meta_description_en' => 'Spacious tent for group trips',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسة بر مع طاولة',
                'name_en' => 'Outdoor Seating with Table',
                'description_ar' => 'مجموعة جلسة بر مع طاولة',
                'description_en' => 'Outdoor seating set with table',
                'slug_ar' => 'جلسة-بر-مع-طاولة',
                'slug_en' => 'outdoor-seating-with-table',
                'category_id' => $seating->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'جلسة بر مع طاولة',
                'meta_title_en' => 'Outdoor Seating with Table',
                'meta_description_ar' => 'مجموعة كاملة للاستجمام الخارجي',
                'meta_description_en' => 'Complete set for outdoor relaxation',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'قماش للستائر',
                'name_en' => 'Curtain Fabric',
                'description_ar' => 'قماش جميل للستائر والديكور',
                'description_en' => 'Beautiful fabric for curtains and decor',
                'slug_ar' => 'قماش-للستائر',
                'slug_en' => 'curtain-fabric',
                'category_id' => $fabrics->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'قماش للستائر',
                'meta_title_en' => 'Curtain Fabric',
                'meta_description_ar' => 'قماش عالي الجودة للديكور المنزلي',
                'meta_description_en' => 'High quality fabric for home decor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'خيمة بر مضادة للمطر',
                'name_en' => 'Rainproof Tent',
                'description_ar' => 'خيمة بر مقاومة للمطر',
                'description_en' => 'Tent resistant to rain',
                'slug_ar' => 'خيمة-بر-مضادة-للمطر',
                'slug_en' => 'rainproof-tent',
                'category_id' => $tents->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'خيمة بر مضادة للمطر',
                'meta_title_en' => 'Rainproof Tent',
                'meta_description_ar' => 'خيمة مثالية للطقس الممطر',
                'meta_description_en' => 'Perfect tent for rainy weather',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name_ar' => 'جلسة بر مريحة',
                'name_en' => 'Comfortable Outdoor Bench',
                'description_ar' => 'مقعد بر مريح للاسترخاء',
                'description_en' => 'Comfortable outdoor bench for relaxation',
                'slug_ar' => 'جلسة-بر-مريحة',
                'slug_en' => 'comfortable-outdoor-bench',
                'category_id' => $seating->id,
                'brand_id' => $khayma_Brand->id,
                'is_published' => true,
                'meta_title_ar' => 'مقعد بر مريح',
                'meta_title_en' => 'Comfortable Outdoor Bench',
                'meta_description_ar' => 'مقعد مثالي للحدائق والمنتزهات',
                'meta_description_en' => 'Ideal bench for gardens and parks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Product::upsert($products, ['slug_ar'], ['name_ar', 'name_en', 'description_ar', 'description_en', 'category_id', 'brand_id', 'is_published', 'meta_title_ar', 'meta_title_en', 'meta_description_ar', 'meta_description_en', 'created_at', 'updated_at']);

    }
}
